#!/usr/bin/env bash

#/ command: korotiuk:mariia: "list variables command"
#/ usage: rerun korotiuk:mariia [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' #No Color
NAME_ARRAY=(RERUN RERUN_VERSION RERUN_MODULES RERUN_MODULE_DIR)
VALUE_ARRAY=($RERUN $RERUN_VERSION $RERUN_MODULES $RERUN_MODULE_DIR)
for ((i=0; i<4; i++)) do
  printf "${RED}${NAME_ARRAY[$i]}: ${GREEN}${VALUE_ARRAY[$i]}${NC}\n"
done

. "$RERUN_MODULE_DIR/lib/functions.sh" "mariia" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

